# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- combined-patches

jobs:
- job: Build
  strategy:
    matrix:
      linux:
        imageName: 'ubuntu-16.04'
        isLinux: true
        artifactMatrixID: 'Noxys_Rack_Linux'
      mac:
        imageName: 'macOS-10.14'
        isMac: true
        artifactMatrixID: 'Noxys_Rack_Mac'

  pool:
    vmImage: $(imageName)

  steps:
  - checkout: self
    submodules: recursive

  - bash: |
      echo `uname -a`
      echo `cat /proc/cpuinfo`
      echo `free -tm`
    displayName: 'System Info'
    condition: variables.isLinux

  - bash: |
      sudo apt install git gdb curl cmake libx11-dev libglu1-mesa-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev zlib1g-dev libasound2-dev libgtk2.0-dev libjack-jackd2-dev jq
    displayName: 'Installing prerequisites'
    condition: variables.isLinux

  - bash: |
      brew install git wget cmake autoconf automake libtool jq python
    displayName: 'Installing prerequisites'
    condition: variables.isMac

  - bash: |
      export SYSTEM=`uname -s` # Tell openssl what system we are building on
      make dep
    displayName: 'Building Dependencies'
    condition: variables.isLinux

  - bash: |
      make dep
    displayName: 'Building Dependencies'
    condition: not(variables.isLinux)

  - bash: |
      sed -i "s/\.dev\./\.noxys\./" Makefile # Make it clear this is not an official release
      make
    displayName: 'Building Rack'

  - bash: |
      cd plugins
      git clone https://github.com/VCVRack/Fundamental.git
      cd Fundamental
      git submodule update --init --recursive
      make dep
      make
      cd ../..
    displayName: 'Building Fundamental Plugins'

  - bash: |
      sed -i 's/codesign/#codesign/' Makefile # We don't have a certificate so just not sign it?
      make dist
      rm -rf Rack Rack-SDK Rack.app # We only care about the packed files
    displayName: 'Creating Distribution Package'

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: $(artifactMatrixID)
      targetPath: 'dist/'
    displayName: Publish Artifact
