# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- combined-patches

jobs:
- job: Build
  strategy:
    matrix:
      linux:
        imageName: 'ubuntu-16.04'
        isLinux: true
        artifactMatrixID: 'NOXYS_RACK_ZIP_LINUX'  

  pool:
    vmImage: $(imageName)

  steps:
  - checkout: self
    submodules: recursive

  - bash: |
      echo `uname -a`
      echo `uname -s`
    displayName: 'System info'

  - bash: |
      sudo apt install git gdb curl cmake libx11-dev libglu1-mesa-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev zlib1g-dev libasound2-dev libgtk2.0-dev libjack-jackd2-dev jq
    displayName: 'Installing prerequisites'
    condition: variables.isLinux

  - bash: |
      export SYSTEM=`uname -s`
      make dep
    displayName: 'Building Dependencies'

  - bash: |
      make
    displayName: 'Building Rack'
